# Generated by Django 2.2.4 on 2020-03-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0004_photoprodutoafterbefore_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprodutoafterbefore',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
