# Generated by Django 2.2.4 on 2020-03-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_auto_20200308_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cases',
        ),
    ]
