# Generated by Django 2.2.4 on 2020-03-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_how_use_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='How_Use_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='video_description',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
