# Generated by Django 3.0.3 on 2020-03-09 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_tecdashimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecdashimages',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
