# Generated by Django 2.2.4 on 2020-03-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_delete_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initial',
            name='subtitle',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='initial',
            name='title',
            field=models.TextField(),
        ),
    ]
