# Generated by Django 3.0.4 on 2020-03-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_tecdashimages_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPrize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='image/products_img')),
                ('preco_one', models.CharField(max_length=60, null=True)),
                ('por_div', models.CharField(max_length=60, null=True)),
                ('prize_div', models.CharField(max_length=80, null=True)),
                ('buy_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
