# Generated by Django 3.0.4 on 2020-03-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information_Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('name_client', models.CharField(max_length=255)),
                ('details_client', models.TextField()),
            ],
        ),
    ]
