# Generated by Django 3.0.3 on 2020-03-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicial', '0003_photoprodutoafterbefore'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoprodutoafterbefore',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
